const FILM_CREDITS = {
  interstellar: [
    'DIRECTOR // Christopher Nolan',
    'WRITERS // Jonathan Nolan, Christopher Nolan',
    'MUSIC // Hans Zimmer',
    'CINEMATOGRAPHY // Hoyte van Hoytema',
    'EDITING // Lee Smith',
    'PRODUCTION DESIGN // Nathan Crowley',
    'STARRING // Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine',
  ],
  inception: [
    'DIRECTOR // Christopher Nolan',
    'WRITER // Christopher Nolan',
    'MUSIC // Hans Zimmer',
    'CINEMATOGRAPHY // Wally Pfister',
    'EDITING // Lee Smith',
    'PRODUCTION DESIGN // Guy Hendrix Dyas',
    'STARRING // Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy',
  ],
  tenet: [
    'DIRECTOR // Christopher Nolan',
    'WRITER // Christopher Nolan',
    'MUSIC // Ludwig Goransson',
    'CINEMATOGRAPHY // Hoyte van Hoytema',
    'EDITING // Jennifer Lame',
    'PRODUCTION DESIGN // Nathan Crowley',
    'STARRING // John David Washington, Robert Pattinson, Elizabeth Debicki, Kenneth Branagh',
  ],
  memento: [
    'DIRECTOR // Christopher Nolan',
    'WRITERS // Christopher Nolan, Jonathan Nolan (story)',
    'MUSIC // David Julyan',
    'CINEMATOGRAPHY // Wally Pfister',
    'EDITING // Dody Dorn',
    'PRODUCTION DESIGN // Patti Podesta',
    'STARRING // Guy Pearce, Carrie-Anne Moss, Joe Pantoliano',
  ],
  'batman-begins': [
    'DIRECTOR // Christopher Nolan',
    'WRITERS // Christopher Nolan, David S. Goyer',
    'MUSIC // Hans Zimmer, James Newton Howard',
    'CINEMATOGRAPHY // Wally Pfister',
    'EDITING // Lee Smith',
    'PRODUCTION DESIGN // Nathan Crowley',
    'STARRING // Christian Bale, Michael Caine, Liam Neeson, Katie Holmes',
  ],
  'the-dark-knight': [
    'DIRECTOR // Christopher Nolan',
    'WRITERS // Jonathan Nolan, Christopher Nolan, David S. Goyer',
    'MUSIC // Hans Zimmer, James Newton Howard',
    'CINEMATOGRAPHY // Wally Pfister',
    'EDITING // Lee Smith',
    'PRODUCTION DESIGN // Nathan Crowley',
    'STARRING // Christian Bale, Heath Ledger, Aaron Eckhart, Gary Oldman',
  ],
  'the-dark-knight-rises': [
    'DIRECTOR // Christopher Nolan',
    'WRITERS // Jonathan Nolan, Christopher Nolan, David S. Goyer',
    'MUSIC // Hans Zimmer',
    'CINEMATOGRAPHY // Wally Pfister',
    'EDITING // Lee Smith',
    'PRODUCTION DESIGN // Nathan Crowley',
    'STARRING // Christian Bale, Tom Hardy, Anne Hathaway, Gary Oldman',
  ],
  oppenheimer: [
    'DIRECTOR // Christopher Nolan',
    'WRITER // Christopher Nolan',
    'MUSIC // Ludwig Goransson',
    'CINEMATOGRAPHY // Hoyte van Hoytema',
    'EDITING // Jennifer Lame',
    'PRODUCTION DESIGN // Ruth De Jong',
    'STARRING // Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.',
  ],
}

export function getFilmCreditLines(film) {
  return FILM_CREDITS[film?.id] || [
    'DIRECTOR // Christopher Nolan',
    'SELECTED PRODUCTION CREDITS',
  ]
}
